// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckActiveUser(arg1:string,arg2:string):Promise<{[key: string]: string}>;
